// build.js — bundles core.js + solver.js + generator.js into bundle.js, a
// single browser script (no modules, no Node imports) that exposes
// `generatePuzzle` globally so index.html can generate puzzles in the browser.
//
//   node build.js
//
// Run this whenever core.js / solver.js / generator.js change, then commit the
// regenerated bundle.js.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(here, f), 'utf8');

// Convert an ES-module source into a plain script fragment:
//   - drop `import ...` lines (everything is bundled into one scope)
//   - drop the `export ` keyword
//   - optionally cut a trailing CLI section (marked by a `// CLI: node` comment)
//   - drop the Node-only top-level `const HERE = dirname(...)` line
function browserify(src, { cutCli = false } = {}) {
  let s = src;
  // Strip import statements (single- or multi-line): `import { a, b } from 'x'`.
  s = s.replace(/import\b[\s\S]*?from\s*['"][^'"]*['"]\s*;?/g, '');
  // Strip the `export ` keyword off declarations.
  s = s.replace(/^export\s+/gm, '');
  if (cutCli) {
    const idx = s.indexOf('// CLI: node');
    if (idx >= 0) s = s.slice(0, idx);
  }
  s = s.replace(
    /const HERE = dirname\(fileURLToPath\(import\.meta\.url\)\);\s*\n/,
    ''
  );
  return s;
}

const bundle = [
  '// bundle.js — generated by build.js, do not edit by hand.',
  '// Exposes window.generatePuzzle / classifyDifficulty / DIFFICULTIES.',
  '(function () {',
  '  "use strict";',
  browserify(read('core.js')),
  browserify(read('solver.js'), { cutCli: true }),
  browserify(read('generator.js'), { cutCli: true }),
  '  globalThis.generatePuzzle = generatePuzzle;',
  '  globalThis.classifyDifficulty = classifyDifficulty;',
  '  globalThis.DIFFICULTIES = DIFFICULTIES;',
  '})();',
  '',
].join('\n');

writeFileSync(join(here, 'bundle.js'), bundle);
console.log('bundle.js written');
